[WIP] Announcements and Monitoring of DST
resonatehq/resonate pull request #269
Opened 2024-04-02 11:48 UTC by vaibhawvipul

- draft PR

2024-04-02 15:06 UTC, dtornow commented on internal/announcements/announce.go
> +		Initialize(Dst)
Do not implicitly create an instance but assert that the instance is not null

2024-04-02 15:06 UTC, dtornow commented on cmd/dst/run.go
> +			announcements.Initialize(announcements.Dst)
Add `announcements.Initialize(announcements.Nop)` to production path

2024-04-02 15:06 UTC, dtornow commented on internal/app/subsystems/aio/network/network_dst.go
> +				event := announcements.NewEvent("HTTPResponse")
We need to announce more information about the HttpRequest e.g. url, method, etc to be able to route and assert in model

2024-04-03 00:08 UTC, dfarr commented on internal/announcements/announce.go
> +type NopAnnouncement struct{}
I hate to be that guy but should this be `NoopAnnouncement` (I know I know, different amount of letters)

2024-04-18 03:57 UTC, dtornow commented
A few suggestions:

# Monitors

Make `Monitor` an interface with a method
- `apply(event Event)`
- `status() []error`

Source internal/announcements/monitor.go

# Announcement

Extend the `Announcement` interface with a method
- `register(monitor *Monitor)`

register is a Noop for Noop and adds a monitor to DstAnnouncement.

On announce, iterate over all monitors an apply the event

**Note**

I believe `Announce` and `GetAnnouncements` do not need to be thread safe because they can only be accessed from one thread to begin with

*if this is not true, please discuss, then my mental model is incomplete*

2024-04-24 03:33 UTC, dtornow requested changes

2024-04-24 03:33 UTC, dtornow commented on internal/announcements/monitors/taskmonitor.go
> +	tm.eventTypeCount[event.Type]++
This is the right idea: When an event happens, modify a counter. When we check the monitors at the end of the run, here we want taskCreated == taskCompleted. If that check is too aggressive, at least we want to check that taskCreated >= taskCompleted

```
if event.Type == "TaskCreated" {
  tm.taskCreated ++
}
if event.Type == "TaskCompleted" {
  tm.taskCompleted ++
}
```

2024-04-24 03:33 UTC, dtornow commented on internal/announcements/monitor.go
> +type Monitors interface {
I would rename the interface to `Monitor` instead of `Monitors` (to the object not the verb)

2024-04-24 03:33 UTC, dtornow commented on internal/app/subsystems/aio/network/network_dst.go
> +				event := announcements.NewEvent("HTTPResponse")
Good!!

2024-04-24 03:33 UTC, dtornow commented on internal/announcements/monitors/taskmonitor.go
> +type taskMonitor struct {
TaskMonitor must not part of the core package for announcements and monitors, but part of the test/dst -- it's application specific

2024-05-07 17:13 UTC, susarlanikhilesh commented on internal/announcements/announce.go
> +	mutex         sync.Mutex // Mutex for thread safety
Usually a better practice to have the mutex the start of the struct. 
As the struct need not calculate the offset every time to find the mutex variable inside the struct.

2024-05-23 01:29 UTC, closed without merging