add --version option to the rootCmd
resonatehq/resonate pull request #301
Opened 2024-04-29 15:23 UTC by N4r35h

resolved issue #298 

its already built into cobra just needed to add the Version string to the rootCommand

![image](https://github.com/resonatehq/resonate/assets/45840495/3515b7ae-e681-4f0e-8dca-9898c3812f14)

2024-04-29 16:05 UTC, guergabo commented
Hi, 

Thanks for this! I was thinking of using go's build process for this issue instead and pass the versioning information to the linker via `ldflags`. That way it's not so static and we can configure it externally from a github workflow. 

It could default to dev or something of the sorts. 

Feel free to explore this route and update this PR. Thanks.

2024-04-30 00:26 UTC, N4r35h commented
sure i have made the changes please refer to the image and let me know if we should add something else or change things around

i added the vsc.version (automatically set by go build) which is the commit hash also feeling it might be useful where we distribute dev versions of the build for testing and want to correlate to the particular commit also seen it done by the docker cli, we can add more info such as version of golang it was compiled with and built time if required

could you explain about the github release workflow or confirm if thats being used right now ?

`go build -ldflags="-X github.com/resonatehq/resonate/cmd/version.Version=v0.5.0"`

![image](https://github.com/resonatehq/resonate/assets/45840495/a4f9b180-fd6f-46e2-9413-22d423004bf2)

2024-04-30 00:31 UTC, guergabo requested changes

2024-04-30 00:31 UTC, guergabo commented on cmd/version/version.go
> +	Use: "version",
no need to make a whole command out of this a variable should do. check this out: https://www.digitalocean.com/community/tutorials/using-ldflags-to-set-version-information-for-go-applications

2024-04-30 00:31 UTC, guergabo commented on cmd/root.go
> +	rootCmd.AddCommand(version.VersionCmd)
the behavior should still remain a flag: `resonate --version`

2024-04-30 00:39 UTC, guergabo commented
regarding the github release workflow, it starts here: https://github.com/resonatehq/resonate/blob/main/.github/workflows/release.yaml

let me take a look in the morning and suggest some follow up actions, because we would want the version information passed to both our `docker image release build` & `github release artifact build`

2024-04-30 00:47 UTC, guergabo commented
ok, for docker image release build:
- most likely `--build-arg` should do the job and use environment variable for this build: https://github.com/resonatehq/resonate/blob/main/Dockerfile#L7

for github release build: 
- we just switched to nix and the ldflags are passed here: https://github.com/resonatehq/resonate/blob/main/flake.nix#L88 
- for this i want to defer to @lucperkins to suggest the best approach to pass an argument.

2024-04-30 00:50 UTC, N4r35h commented
thanks for pointing out the flake.nix file

i have made the requested changes consider it a draft let me know if anything else is required
i will look into setting this into the workflow in a while

2024-04-30 00:52 UTC, guergabo requested changes

2024-04-30 00:52 UTC, guergabo commented on cmd/root.go
> +func computeVersion() string {
check out the link i sent before, i'll paste here again: https://www.digitalocean.com/community/tutorials/using-ldflags-to-set-version-information-for-go-applications

this whole function is not needed.

2024-05-03 00:03 UTC, closed without merging