add: limit while scheduling promises
resonatehq/resonate pull request #307
Opened 2024-05-03 11:10 UTC by aneessh18

This PR addresses the concerns of this issue https://github.com/resonatehq/resonate/issues/169. 

More information: right now the kernel processes schedules from the databases every 10 ms and creates promises for execution. It finds out the list of promises to be scheduled by executing the READ_ALL_SCHEDULES query against the respective database. This is prone to occur when the system is under high stress as the query can degrade performance when there are a huge number of promises to be scheduled. Instead, this PR ensures that only a limited number of them are scheduled without the system getting overwhelmed. 

Testing
1. I've run the local build and put log statements for recording the number of results in the readSchedules method and I was able to verify that the number of scheduled promises is pegged at the limit. 
2. Unit tests

2024-05-04 23:12 UTC, dfarr requested changes
Thank you so much again @aneessh18!!!

Do you mind adding the schedule batch size configuration to our deterministic simulation testing (DST) flags? We would need to add it [here](https://github.com/resonatehq/resonate/blob/main/cmd/dst/run.go#L269-L275), the range flag generates a random number for the config value between the min and the max. It would also be useful to print out this config value [here](https://github.com/resonatehq/resonate/blob/main/internal/kernel/system/system.go#L24-L31), this helps compare two runs of our DST to ensure that the configuration value is the same.

You can try the DST locally!
```
go run ./... dst run
```

2024-05-04 23:12 UTC, dfarr commented on cmd/serve/serve.go
> +	cmd.Flags().Int("system-max-schedules-size", 10000, "max number of schedules to process on each tick")
Mind renaming this?

```suggestion
	cmd.Flags().Int("system-schedule-batch-size", 10000, "max number of schedules to process on each tick")
```

2024-05-04 23:12 UTC, dfarr commented on cmd/serve/serve.go
> +	_ = viper.BindPFlag("system.maxSchedulesSize", cmd.Flags().Lookup("system-max-schedules-size"))
```suggestion
	_ = viper.BindPFlag("system.scheduleBatchSize", cmd.Flags().Lookup("system-max-schedules-size"))
```

2024-05-04 23:12 UTC, dfarr commented on internal/kernel/system/system.go
> +	MaxSchedulesSize      int
```suggestion
	ScheduleBatchSize      int
```

2024-05-05 07:19 UTC, aneessh18 commented
> Thank you so much again @aneessh18!!!
> 
> Do you mind adding the schedule batch size configuration to our deterministic simulation testing (DST) flags? We would need to add it [here](https://github.com/resonatehq/resonate/blob/main/cmd/dst/run.go#L269-L275), the range flag generates a random number for the config value between the min and the max. It would also be useful to print out this config value [here](https://github.com/resonatehq/resonate/blob/main/internal/kernel/system/system.go#L24-L31), this helps compare two runs of our DST to ensure that the configuration value is the same.
> 
> You can try the DST locally!
> 
> ```
> go run ./... dst run
> ```

Thanks for reviewing this MR. Added the flags in DST.

2024-05-05 07:19 UTC, aneessh18 commented on cmd/serve/serve.go
> +	cmd.Flags().Int("system-max-schedules-size", 10000, "max number of schedules to process on each tick")
Done

2024-05-06 15:55 UTC, dfarr approved these changes
🎉

2024-05-06 21:21 UTC, merged