add strict flag for assert
resonatehq/resonate pull request #329
Opened 2024-05-16 05:42 UTC by susarlanikhilesh

Addresses [Issue](https://github.com/resonatehq/resonate/issues/112)

2024-05-16 15:54 UTC, dfarr commented
Thank you so much @susarlanikhilesh 🎉 🎉 

The tests are failing because some of our tests expect a panic to occur, and if the flag is not set (eg: the code is run via a test rather than cli) I believe viper is returning the default boolean value of `false`. Is there a way to check if the flag is not set and, if not, set strict to true instead?

2024-05-16 17:09 UTC, susarlanikhilesh commented
Yes the strict flag is false, I did set when panic is true in the test cases

2024-05-16 17:15 UTC, dfarr commented
I would prefer for `strict=true` in cases where not explicitly set. Our philosophy here is to panic by default when an unexpected event occurs, this way we can protect ourselves from being in an invalid state.

```
viper.GetBool("strict") // if not set needs to be defaulted to true
```

An easier way to do it might be to invert the name of the flag to something like `ignore-asserts` that we can default to false which makes things a little easier to implement.

2024-05-17 22:49 UTC, dfarr requested changes

2024-05-17 22:49 UTC, dfarr commented on internal/util/util.go
> +	strict := viper.GetBool("ignore-asserts")
```suggestion
	ignoreAsserts := viper.GetBool("ignore-asserts")
```

2024-05-17 22:49 UTC, dfarr commented on internal/util/util.go
> +	if !strict && !cond {
```suggestion
	if !ignoreAsserts && !cond {
```

2024-05-20 17:29 UTC, dfarr approved these changes

2024-05-20 17:32 UTC, merged