add claim and complete task
resonatehq/resonate pull request #443
Opened 2024-10-17 05:18 UTC by TusharMohapatra07

- This PR is linked to issue #436 . I've implemented the claim and complete task.
- Need some help in the following areas:
  1. found an endpoint for hearbeatTasks.go (https://github.com/resonatehq/resonate/blob/main/internal/app/coroutines/heartbeatTasks.go) but according to the documentation (https://resonatehq.github.io/resonate/#tag/Tasks/operation/completeTask), its a post request requiring just the process-id. Unable to find the endpoint to map id and counter with
  2. If this implementation is correct, I need to pass a type that implements `gocoro.Coroutine[*t_aio.Submission, *t_aio.Completion, any]`. In tasks.go i need to register these commands in order for them to work. I've so far figured out that gocoro.newCoroutine with signature `func[T, TNext, TReturn any](f CoroutineFunc[T, TNext, TReturn], r map[string]any) *coroutine[T, TNext, TReturn]` creates a coroutine of this type. But i'm unable to figure out what to pass in place of f and r

2024-10-17 19:56 UTC, dfarr commented
Thank you @TusharMohapatra07!!!

The scaffolding here looks great, exactly what we need. But we do need to use the openapi auto generated client here, not the `Request`/`Response` objects which are internal facing structures for the server only. Here the cli is acting as a client and getting a response back from the server.

The promise cli command and schedule cli commands should be good guides, for example let's take a look at [promise create](https://github.com/resonatehq/resonate/blob/main/cmd/promises/create.go).

1. Pass the client in to the command as a [function parameter](https://github.com/resonatehq/resonate/blob/main/cmd/promises/create.go#L21)
2. Take all the command line arguments and construct a params/body struct to pass to the [generated function](https://github.com/resonatehq/resonate/blob/main/cmd/promises/create.go#L69) (there will be functions corresponding to tasks.
3. Grab the response and print a corresponding status message

You may find our api specifiction docs [here](https://resonatehq.github.io/resonate/#tag/Tasks/operation/claimTask) handy too. Let me know if I can help further!

2024-10-18 13:03 UTC, TusharMohapatra07 commented
@dfarr So, i need to use the functions present in github.com/resonatehq/resonate/pkg/client/v1. correct ?

2024-10-18 15:41 UTC, dfarr commented
> @dfarr So, i need to use the functions present in github.com/resonatehq/resonate/pkg/client/v1. correct ?

Correct!

2024-10-18 16:59 UTC, TusharMohapatra07 commented
@dfarr on it.

2024-10-19 05:09 UTC, TusharMohapatra07 commented
@dfarr please review and suggest changes (if any).

2024-10-20 23:24 UTC, dfarr requested changes
This looks really good! I have a few small requests.

One additional though, for `promises` and `schedules` the id parameter is a positional parameter (see [here](https://github.com/resonatehq/resonate/blob/main/cmd/promises/get.go#L22-L30)), I'm wondering if we should take a similar approach for tasks to be consistent, what do you think?

2024-10-20 23:24 UTC, dfarr commented on cmd/tasks/claim.go
> +				Ttl:       int64(ttl.Milliseconds()), // Convert duration to milliseconds
I believe `ttl.Milliseconds()` is already an int64 so we shouldn't have to convert it

2024-10-20 23:24 UTC, dfarr commented on cmd/tasks/claim.go
> +			} else if res.StatusCode() == 403 {
For consistency, I think we should [print the entire body](https://github.com/resonatehq/resonate/blob/main/cmd/promises/get.go#L37-L40) if the status code is not 201, this is what we do for promises and schedules and will keep our cli more flexible to changes. Could we follow the same pattern for all task commands?

2024-10-21 13:14 UTC, TusharMohapatra07 commented
@dfarr I think having id as positional parameter consistently throughout the application enchances the user experience a lot. i'm implementing those changes you requested.

2024-10-21 13:23 UTC, TusharMohapatra07 commented
@dfarr please review

2024-10-22 01:21 UTC, dfarr commented
Very good! Only one thing, the heartbeat request takes a single parameter of `--process-id`, whichever process id is specified on claim can be used to heartbeat, this way a client can claim a bunch of tasks and batch heartbeat with a single process id.

```
resonate tasks heartbeat --process-id foo
```

It must be hard to test this! Here is how I do it, maybe this will help
```
# start the server
go run ./... serve

# create a promise and a task
go run ./... promises create foo --timeout 24h --tag resonate:invoke=poll://default

# claim the task (the id is auto incrementing, so will be 1)
go run ./... tasks claim 1 --counter 1 --process-id foo --ttl 1m

# complete the task (if not completed in one minute, will need to be re-claimed, the counter will be bumped)
go run ./... tasks complete 1 --counter 1
```

If you have a sqlite db editor you can open up the db file (defaults to `resonate.db`) and inspect the tasks table to see how the cli command affects tasks.

One more nitpick, we don't need the request id for the cli. It doesn't hurt to keep it so I am of two minds on this one, but getting rid of it as a flag might make the cli a little simpler.

2024-10-22 01:40 UTC, TusharMohapatra07 commented
@dfarr I'll get rid of requestId. Sorry but i'm not clear about the first requirement. What should i do with the process-id ?   I'm not clear what changes i need to implement.

2024-10-22 15:36 UTC, TusharMohapatra07 commented
@dfarr please review

2024-10-23 00:03 UTC, dfarr reviewed
🎉

2024-10-23 00:08 UTC, merged