Added Callback cli
resonatehq/resonate pull request #446
Opened 2024-10-24 16:03 UTC by Madraceee

### Description
Added callback cli. Invokes the inbuilt commands.

**This is not finished**

1. What should the value of requestID be. UUID or some string? 
2. For url and default, how should those values be passed?

Sry I was busy with my work, could not look into what should be passed for callbacks which dont require a json

2024-10-24 16:06 UTC, Madraceee commented
@dfarr I couldnt find an option to request for review , so can you help me out?

2024-11-04 22:18 UTC, dfarr requested changes
So sorry for the delay in getting back to you on this PR. The `recv` flag is so tricky because it can be either a string or a json object in the form `{"type": "", data: {}}`.

I played around a little with this, what do you think about this approach?

```go
var recv v1.Recv

if json.Valid([]byte(recvStr)) {
	var recv0 v1.Recv0

	if err := json.Unmarshal([]byte(recvStr), &recv0); err != nil {
		return err
	}
	if err := recv.FromRecv0(recv0); err != nil {
		return err
	}
} else {
	if err := recv.FromRecv1(recvStr); err != nil {
		return err
	}
}
```

This unmarshals the provided value to a `v1.Recv0` if the value provided by the user is valid json, otherwise we assume it's a string. That way the user can provide one or the other, for example:

```
# string example
go run ./... callbacks create --promise-id foo --root-promise-id bar --recv default

# json example
go run ./... callbacks create --promise-id foo --root-promise-id bar --recv '{"type":"poll", "data":{"group":"default","id":"0"}}'
```

2024-11-04 22:18 UTC, dfarr commented on cmd/callbacks/create.go
> +			paramsByte, err := json.Marshal(struct {
We can remove requestId from the CLI, its an optional parameter that is more handy for web applications, you can pass nil to CreateCallbackWithResponse for the params.

2024-11-04 22:18 UTC, dfarr commented on cmd/callbacks/create.go
> +	cmd.Flags().StringVar(&promiseId, "promise-id", "", "promise id")
We can mark this one as required

2024-11-04 22:18 UTC, dfarr commented on cmd/callbacks/create.go
> +	cmd.Flags().StringVar(&rootPromiseId, "root-promise-id", "", "root promise id")
We can also mark this one as required

2024-11-04 22:18 UTC, dfarr commented on cmd/callbacks/create.go
> +	cmd.Flags().DurationVar(&timeout, "timeout", 0, "callback timeout")
I think we can put a sensible default here, maybe 1m?

2024-11-04 22:18 UTC, dfarr commented on cmd/callbacks/create.go
> +	cmd.Flags().StringVar(&recv, "recv", "", "receive object")
We can put default (literally) as the default for recv

2024-11-08 06:40 UTC, Madraceee commented
I am not well. I will look into this next week. Is that fine?

2024-11-10 19:31 UTC, dfarr commented
> I am not well. I will look into this next week. Is that fine?

Of course, take your time and hope you get well soon!

2024-12-18 03:46 UTC, dfarr commented
Hey @Madraceee I can take over this PR if you'd like? Let me know your status :)

2024-12-18 20:07 UTC, dfarr commented
Closing in favour of #499

2024-12-18 20:07 UTC, closed without merging