Avillega/deduplicate callbacks
resonatehq/resonate pull request #478
Opened 2024-12-09 22:15 UTC by avillega

2024-12-09 23:22 UTC, dfarr requested changes

2024-12-09 23:22 UTC, dfarr commented on internal/app/coroutines/createCallback.go
> +				status = t_api.StatusCreated
Should this be set in the if branch above and the else branch omitted?

2024-12-09 23:33 UTC, avillega commented on internal/app/coroutines/createCallback.go
> +				status = t_api.StatusCreated
Done!

2024-12-10 00:12 UTC, dfarr approved these changes

2024-12-10 00:15 UTC, merged